// Generated by Wrangler by running `wrangler types`

interface Env {
	KV: KVNamespace;
	API_AUTH_TOKEN: "test-token";
	BROWSER_RENDERING_TOKEN: "browser-token";
	SLACK_WEBHOOK_URL: "";
	SITE_CRAWLER: DurableObjectNamespace<import("./src/index").SiteCrawler>;
	JOB_MONITOR: DurableObjectNamespace<import("./src/index").JobMonitor>;
	R2: R2Bucket;
	DB: D1Database;
	SERVICE: Fetcher;
	VECTORIZE_INDEX: VectorizeIndex;
	MYBROWSER: Fetcher;
	AI: Ai;
	DISCOVERY_WORKFLOW: Workflow;
	JOB_MONITOR_WORKFLOW: Workflow;
	CHANGE_ANALYSIS_WORKFLOW: Workflow;
}
