/**
 * @fileoverview Crypto Constants
 *
 * Shared constants for cryptographic operations across all domains.
 *
 * @author 9to5 Scout AI Team
 * @version 1.0.0
 * @since 2024-01-01
 */

export const CRYPTO_CONSTANTS = {
  DEFAULT_UUID_LENGTH: 36,
  DEFAULT_TOKEN_LENGTH: 32,
  DEFAULT_API_KEY_LENGTH: 32,
  DEFAULT_SESSION_TOKEN_LENGTH: 64,
  DEFAULT_CSRF_TOKEN_LENGTH: 32,
  DEFAULT_NONCE_LENGTH: 16,
  DEFAULT_SALT_LENGTH: 16,
  DEFAULT_IV_LENGTH: 16,
  DEFAULT_KEY_LENGTH: 32,
  DEFAULT_SECRET_LENGTH: 64,
  DEFAULT_PASSWORD_LENGTH: 12,
  DEFAULT_OTP_LENGTH: 6,
  DEFAULT_VERIFICATION_CODE_LENGTH: 6,
  DEFAULT_CONFIRMATION_CODE_LENGTH: 6,
  DEFAULT_ACTIVATION_CODE_LENGTH: 6,
  DEFAULT_RECOVERY_CODE_LENGTH: 8,
  DEFAULT_BACKUP_CODE_LENGTH: 8,
  DEFAULT_ACCESS_CODE_LENGTH: 8,
  DEFAULT_INVITATION_CODE_LENGTH: 8,
  DEFAULT_REFERRAL_CODE_LENGTH: 8,
  DEFAULT_PROMO_CODE_LENGTH: 8,
  DEFAULT_COUPON_CODE_LENGTH: 8,
  DEFAULT_DISCOUNT_CODE_LENGTH: 8,
  DEFAULT_VOUCHER_CODE_LENGTH: 8,
  DEFAULT_GIFT_CODE_LENGTH: 8,
  DEFAULT_LICENSE_CODE_LENGTH: 16,
  DEFAULT_SERIAL_NUMBER_LENGTH: 16,
  DEFAULT_PART_NUMBER_LENGTH: 12,
  DEFAULT_SKU_LENGTH: 12,
  DEFAULT_BARCODE_LENGTH: 12,
  DEFAULT_QR_CODE_LENGTH: 16,
  DEFAULT_HASH_LENGTH: 32,
  DEFAULT_CHECKSUM_LENGTH: 8,
  DEFAULT_SIGNATURE_LENGTH: 64,
  DEFAULT_FINGERPRINT_LENGTH: 32,
  DEFAULT_DIGEST_LENGTH: 32,
} as const;
